export const soilTestCases = [
  {
    id: "rice_1",
    name: "Rice (wet conditions)",
    expectedCrop: "rice",
    input: {
      N: 90,
      P: 40,
      K: 40,
      temperature: 24,
      humidity: 80,
      ph: 6.5,
      rainfall: 180,
    },
  },
  {
    id: "maize_1",
    name: "Maize (moderate)",
    expectedCrop: "maize",
    input: {
      N: 70,
      P: 45,
      K: 55,
      temperature: 26,
      humidity: 60,
      ph: 6.8,
      rainfall: 85,
    },
  },
  {
    id: "cotton_1",
    name: "Cotton (warm & lower rainfall)",
    expectedCrop: "cotton",
    input: {
      N: 60,
      P: 35,
      K: 50,
      temperature: 30,
      humidity: 55,
      ph: 7.2,
      rainfall: 55,
    },
  },
  {
    id: "chickpea_1",
    name: "Chickpea (cool & drier)",
    expectedCrop: "chickpea",
    input: {
      N: 40,
      P: 55,
      K: 45,
      temperature: 20,
      humidity: 45,
      ph: 7.0,
      rainfall: 45,
    },
  },
];

export const productTemplates = [
  {
    id: "seed_rice",
    name: "Rice Seeds (High Yield)",
    price: 149,
    category: "Seeds",
    stock: 200,
    description: "Certified rice seeds suitable for recommended soil conditions.",
    image: "https://images.unsplash.com/photo-1604335399105-0f81d2a4b6c9?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "seed_maize",
    name: "Maize Seeds (Hybrid)",
    price: 179,
    category: "Seeds",
    stock: 200,
    description: "Hybrid maize seeds for strong germination and uniform crop stand.",
    image: "https://images.unsplash.com/photo-1602526216039-2a9f7d4e9d2b?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "seed_cotton",
    name: "Cotton Seeds (Bt)",
    price: 199,
    category: "Seeds",
    stock: 150,
    description: "Bt cotton seeds for warm climates. Follow local guidelines.",
    image: "https://images.unsplash.com/photo-1523349122880-444c3b1b2f9a?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "seed_chickpea",
    name: "Chickpea Seeds (Desi)",
    price: 159,
    category: "Seeds",
    stock: 180,
    description: "Chickpea (gram) seeds suited for cool & drier seasons.",
    image: "https://images.unsplash.com/photo-1615484477778-ca3b77940c25?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "soil_kit_basic",
    name: "Soil Test Kit (Basic)",
    price: 299,
    category: "Soil Kits",
    stock: 50,
    description: "Basic NPK + pH soil testing kit for home and farm use.",
    image: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "fert_nitrogen",
    name: "Nitrogen Fertilizer (Urea 46%)",
    price: 499,
    category: "Fertilizers",
    stock: 80,
    description: "Nitrogen-rich fertilizer to improve vegetative growth. Use as per soil report.",
    image: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "fert_phosphorus",
    name: "Phosphorus Fertilizer (DAP)",
    price: 599,
    category: "Fertilizers",
    stock: 60,
    description: "Supports root development and early growth. Apply as recommended.",
    image: "https://images.unsplash.com/photo-1615474634822-2034d86f7d40?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "fert_potassium",
    name: "Potassium Fertilizer (MOP)",
    price: 549,
    category: "Fertilizers",
    stock: 60,
    description: "Improves plant strength and stress tolerance. Apply as per guidance.",
    image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "irrigation_drip",
    name: "Drip Irrigation Starter Set",
    price: 899,
    category: "Irrigation",
    stock: 25,
    description: "Starter kit for drip irrigation—ideal for low-rainfall conditions.",
    image: "https://images.unsplash.com/photo-1591154669695-5f2a8d20c089?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "tools_hand_trowel",
    name: "Garden Hand Trowel (Steel)",
    price: 199,
    category: "Tools",
    stock: 120,
    description: "Durable hand trowel for planting and soil mixing.",
    image: "https://images.unsplash.com/photo-1611693929125-5f2b10d5c8a3?q=80&w=1200&auto=format&fit=crop",
  },
];

